# Generated by Django 5.1 on 2024-08-10 01:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edifice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('qtd_residences', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='QTD de residências')),
            ],
            options={
                'verbose_name': 'edifício',
                'verbose_name_plural': 'edifícios',
            },
        ),
        migrations.CreateModel(
            name='MonthBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_bill_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor da conta de energia')),
                ('water_bill_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor da conta de água')),
                ('cleaning_bill_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor da taxa de limpeza')),
                ('edifice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edifices.edifice', verbose_name='edifício')),
            ],
            options={
                'verbose_name': 'cobrança mensal',
                'verbose_name_plural': 'cobranças mensais',
            },
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_water_reading', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='última medição de água')),
                ('number', models.IntegerField(verbose_name='número')),
                ('prefix', models.CharField(blank=True, max_length=20)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('edifice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edifices.edifice', verbose_name='edifício')),
            ],
            options={
                'verbose_name': 'residência',
                'verbose_name_plural': 'residências',
            },
        ),
        migrations.CreateModel(
            name='CondominiumBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_water_reading', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='medição da água inicial')),
                ('final_water_reading', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='medição da água final')),
                ('month_billing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edifices.monthbilling', verbose_name='cobrança mensal')),
                ('residence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edifices.residence', verbose_name='residência')),
            ],
        ),
    ]
