# Generated by Django 5.1 on 2024-08-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edifices', '0003_edifice_fixed_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthbilling',
            name='cleaning_material_bill_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor da taxa de material de limpeza'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='prefix',
            field=models.CharField(blank=True, max_length=20, verbose_name='prefixo'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='suffix',
            field=models.CharField(blank=True, max_length=20, verbose_name='sufixo'),
        ),
    ]
