# Generated by Django 5.1 on 2024-08-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edifices', '0004_monthbilling_cleaning_material_bill_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthbilling',
            name='trash_bill_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor da taxa de lixo'),
        ),
    ]
