# Generated by Django 5.1 on 2024-08-11 22:22

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edifices', '0006_monthbilling_iptu_bill_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthbilling',
            name='month',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='mês'),
        ),
        migrations.AlterField(
            model_name='monthbilling',
            name='others_bill_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor da taxa de outros'),
        ),
    ]
