# Generated by Django 5.1 on 2024-08-11 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edifices', '0007_monthbilling_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthbilling',
            name='sewage_bill_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor da taxa de esgoto'),
        ),
    ]
