# Generated by Django 5.1 on 2024-08-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edifices', '0008_monthbilling_sewage_bill_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condominiumbilling',
            options={'verbose_name': 'cobrança de condomínio', 'verbose_name_plural': 'cobranças de condomínio'},
        ),
        migrations.RemoveField(
            model_name='edifice',
            name='qtd_residences',
        ),
    ]
