# Generated by Django 5.1 on 2025-05-02 14:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edifices', '0009_alter_condominiumbilling_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='iptu',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='valor do IPTU'),
        ),
        migrations.AddField(
            model_name='residence',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='valor do aluguel'),
        ),
    ]
