# Generated by Django 5.1 on 2025-05-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edifices', '0010_residence_iptu_residence_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthbilling',
            name='iptu_bill_amount',
        ),
        migrations.AddField(
            model_name='monthbilling',
            name='charge_iptu',
            field=models.BooleanField(default=False, help_text='Marque se deseja cobrar o IPTU do morador', verbose_name='cobrar IPTU?'),
        ),
    ]
