# Generated by Django 5.1 on 2025-05-02 14:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edifices', '0011_remove_monthbilling_iptu_bill_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominiumbilling',
            name='iptu',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor do IPTU'),
        ),
        migrations.AddField(
            model_name='condominiumbilling',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor do aluguel'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='iptu',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor do IPTU'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor do aluguel'),
        ),
    ]
