# Generated by Django 5.1 on 2025-05-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edifices', '0012_condominiumbilling_iptu_condominiumbilling_rent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condominiumbilling',
            name='iptu',
        ),
        migrations.RemoveField(
            model_name='condominiumbilling',
            name='rent',
        ),
    ]
